name: Docker Image

on:
  push:
    branches:
      # Build only the master branch
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v1
    - name: Run tox
      uses: tox-dev/gh-action-tox@master
    - name: Build and push the Docker image
      run: ./build.sh
      env:
        DOCKER_HUB_USERNAME: starcraft66
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
        DOCKER_GH_REGISTRY_URL: "docker.pkg.github.com"
        DOCKER_GH_USERNAME: starcraft66
        DOCKER_GH_PASSWORD: ${{ secrets.GITHUB_TOKEN_OWNED }}
